apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: elasticsearch-service
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/version: "7.17.5"
    app.kubernetes.io/component: search
    app.kubernetes.io/part-of: lilishop
    tier: "middleware"
spec:
  type: NodePort
  ports:
    - name: "9200"
      nodePort: 30920
      port: 9200
      targetPort: es9200
    - name: "9300"
      nodePort: 30930
      port: 9300
      targetPort: es9300
  selector:
    lilishop.service: elasticsearch

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/version: "7.17.5"
    app.kubernetes.io/component: search
    app.kubernetes.io/part-of: lilishop
    tier: "middleware"
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      lilishop.service: elasticsearch
  template:
    metadata:
      labels:
        lilishop.network/stack: "true"
        lilishop.service: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: pubrepo.jiagouyun.com/demo/demo-lilishop-elasticsearch:7.17.5
          env:
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms2g -Xmx4g
          ports:
            - name: es9200
              containerPort: 9200
            - name: es9300
              containerPort: 9300
          resources: {}
          volumeMounts:
            - name: vol-data
              mountPath: /usr/share/elasticsearch/data
            - name: vol-logs
              mountPath: /usr/share/elasticsearch/logs
            - name: vol-ik
              mountPath: /usr/share/elasticsearch/plugins/ik
            - name: vol-plugins-analysis-ik-conf
              mountPath: /usr/share/elasticsearch/plugins/ik/config/IKAnalyzer.cfg.xml
      restartPolicy: Always
      volumes:
        - name: vol-data
          hostPath:
            path: /root/docker/kubernetes/data/middleware/elasticsearch/data
            type: Directory
        - name: vol-logs
          hostPath:
            path: /root/docker/kubernetes/data/middleware/elasticsearch/logs
            type: Directory
        - name: vol-ik
          hostPath:
            path: /root/docker/kubernetes/middleware/elasticsearch/ik
            type: Directory
        - name: vol-plugins-analysis-ik-conf
          hostPath:
            path: /root/docker/kubernetes/middleware/elasticsearch/config/IKAnalyzer.cfg.xml
            type: File
