apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: nacos-service
    app.kubernetes.io/instance: discover
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: lilishop
    tier: "middleware"
spec:
  type: NodePort
  ports:
    - name: "8848"
      port: 8848
      nodePort: 30848
      targetPort: nacos8848
    - port: 9848
      name: client-rpc
      nodePort: 30948
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      nodePort: 30949
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      nodePort: 30748
      targetPort: 7848
  selector:
    lilishop.service: nacos
status:
  loadBalancer: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: lilishop-middleware
data:
  mysql.host: "mysql"
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "lilishop"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/instance: discover
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: lilishop
    tier: "middleware"
spec:
  serviceName: nacos-headless
  replicas: 1
  selector:
    matchLabels:
      lilishop.service: nacos
  template:
    metadata:
      labels:
        lilishop.service: nacos
    spec:
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done",
            ]
      containers:
        - image: nacos/nacos-server:v2.2.0
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "500m"
          env:
            # - name: NACOS_REPLICAS
            #   value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: MYSQL_SERVICE_DB_PARAM
              value: "&connectTimeout=10000&socketTimeout=30000&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: MODE
              value: standalone
            - name: SPRING_DATASOURCE_PLATFORM
              value: mysql
            # - name: NACOS_SERVERS
            #   value: "nacos-0.nacos-headless.lilishop-middleware.svc.cluster.local:8848 nacos-1.nacos-headless.lilishop-middleware.svc.cluster.local:8848 nacos-2.nacos-headless.lilishop-middleware.svc.cluster.local:8848"
          name: nacos
          ports:
            - containerPort: 8848
              name: nacos8848
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
      restartPolicy: Always
