apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.1.2
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            nodePort: 30920 # 公开端口
            port: 9200
            protocol: TCP
            targetPort: 9200
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          initContainers:
            - name: donviewclass-initialize
              command:
                - sh
                - -c
                - |
                  ./bin/elasticsearch-plugin install install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.1.2/elasticsearch-analysis-ik-8.1.2.zip
                  ./bin/elasticsearch-users useradd tsdonviewclass -p tsdonviewclass -r superuser
          volumes:
            - name: elasticsearch-data
              emptyDir: {}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            nodePort: 30601 # 公开端口
            port: 5601
            protocol: TCP
            targetPort: 5601