apiVersion: v1
kind: Service
metadata:
  name: canal-server
  namespace: lilishop-middleware
  labels:
    k8s-app: canal-server
spec:
  type: NodePort
  ports:
    - port: 11111
      nodePort: 30111
      name: "11111"
      targetPort: canal11111
    - port: 11112
      nodePort: 30112
      name: "11112"
      targetPort: cancal11112
  selector:
    k8s-app: canal-server
---
apiVersion: v1
kind: Service
metadata:
  name: canal-admin
  namespace: lilishop-middleware
  labels:
    k8s-app: canal-admin
spec:
  type: NodePort
  ports:
    - port: 8089
      nodePort: 30089
      name: "8089"
      targetPort: canal8089
  selector:
    k8s-app: canal-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-admin
  namespace: lilishop-middleware
spec:
  selector:
    matchLabels:
      app: canal-admin
  template:
    metadata:  
      labels:
        app: canal-admin
    spec:
      containers:
        - env:
            - name: spring.datasource.address
              value: mysql:3306
            - name: spring.datasource.database
              value: canal_manager
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              value: lilishop
          image: canal/canal-admin:v1.1.6
          name: canal-admin
          ports:
            - name: canal8089
              containerPort: 8089

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-server-config
  namespace: lilishop-middleware
data:
  instance.properties: |
      ## mysql serverId
      canal.instance.mysql.slaveId = 1234
      # position info，需要改成自己的数据库信息
      canal.instance.master.address = mysql:3306
      canal.instance.master.journal.name = 
      canal.instance.master.position = 
      canal.instance.master.timestamp = 
      # canal.instance.standby.address = 
      # canal.instance.standby.journal.name =
      # canal.instance.standby.position = 
      # canal.instance.standby.timestamp = 
      # username/password，需要改成自己的数据库信息
      canal.instance.dbUsername = root
      canal.instance.dbPassword = lilishop
      canal.instance.defaultDatabaseName =
      canal.instance.connectionCharset = UTF-8
      #table regex
      canal.instance.filter.regex = .\*\\\\..\*


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: canal-server
  namespace: lilishop-middleware
  labels:
    k8s-app: canal-server
spec:
  serviceName: cancal-server
  replicas: 1
  selector:
    matchLabels:
      k8s-app: canal-server
  template:
    metadata:
      labels:
        k8s-app: canal-server
    spec:
      containers:
        - name: canal-server
          image: canal/canal-server:v1.1.6
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
            - name: STS_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: canal.register.ip
              value: $(POD_NAME).$(SERVICE_NAME)-headless.$(STS_NAMESPACE)
            - name: canal.admin.manage
              value: "canal-admin:8089"
            - name: canal.admin.port
              value: "11110"
            - name: canal.admin.use
              value: admin
            - name: canal.admin.passwd
              value: 4ACFE3202A5FF5CF467898FC58AAB1D615029441
            - name: canal.admin.register.auto
              value: "true"
            - name: canal.admin.register.name
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: canal.admin.register.cluste
              value: local_cluster
          ports:
            - name: canal11111
              containerPort: 11111
            - name: cancal11112
              containerPort: 11112
          # volumeMounts:
          #   - name: canal-config
          #     mountPath: /home/canal/canal-server/conf
          #     readOnly: false
      volumes:
        - name: canal-config
          configMap:
            name: canal-server-config
