apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: logstash-service
    app.kubernetes.io/instance: logstash
    app.kubernetes.io/version: "7.17.5"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: lilishop
    tier : "middleware"
spec:
  type: NodePort
  ports:
    - name: "4560"
      nodePort: 30560
      port: 4560
      targetPort: logstash4560
  selector:
    lilishop.service: logstash
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/instance: logstash
    app.kubernetes.io/version: "7.17.5"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: lilishop
    tier : "middleware"
spec:
  serviceName: logstash
  replicas: 1
  selector:
    matchLabels:
      lilishop.service: logstash
  template:
    metadata:
      labels:
        lilishop.network/stack: "true"
        lilishop.service: logstash
    spec:
      containers:
        - image: logstash:7.17.5
          name: logstash
          ports:
            - name: logstash4560
              containerPort: 4560
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: vol-conf
      restartPolicy: Always
      volumes:
        - name: vol-conf
          hostPath:
              path: /root/docker/kubernetes/middleware/logstash/config/logstash-springboot.conf
              type: File
